Cicedev 233
ciceunicen/core pull request #84
Opened 2024-06-06 20:11 UTC by scianca1

Se agregó un endpoint que sirve para pedir todos los usuarios que quieran ser emprendedores pero aún no están validados en el controlador de Entrepreneur.

2024-06-07 19:14 UTC, Renzo-Guerra requested changes
Me prece que estas usando el *findAll()* que viene por defecto en todos los repository, en vez de utilizar el *findAll(values, deleted)* que vos creaste.  De esta forma te esta trayendo **todos** los usuarios

![image](https://github.com/ciceunicen/core/assets/104610425/ce0148e0-8a6c-4243-a3b4-d8494aaa6bb8)

Fijate que los otros dicen **1 usage**, pero este no está conectado a nada

![image](https://github.com/ciceunicen/core/assets/104610425/a7d68a76-725a-473a-8fbb-c65906c1cc42)

2024-06-07 19:35 UTC, scianca1 commented
Ese no lo cree yo, yo cree findByIs_activeAll() y nose porque pero capas no
hice el push pero en mi versión si lo uso, ahora hago el push a ver si se
cambia

El vie, 7 jun 2024 a la(s) 4:15 p.m., Renzo-Guerra ***@***.***)
escribió:

> ***@***.**** requested changes on this pull request.
>
> Me prece que estas usando el *findAll()* que viene por defecto en todos
> los repository, en vez de utilizar el *findAll(values, deleted)* que vos
> creaste. De esta forma te esta trayendo *todos* los usuarios
>
> image.png (view on web)
> <https://github.com/ciceunicen/core/assets/104610425/ce0148e0-8a6c-4243-a3b4-d8494aaa6bb8>
>
> Fijate que los otros dicen *1 usage*, pero este no está conectado a nada
>
> image.png (view on web)
> <https://github.com/ciceunicen/core/assets/104610425/a7d68a76-725a-473a-8fbb-c65906c1cc42>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ciceunicen/core/pull/84#pullrequestreview-2105220182>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZL2H6YZWG5LZ5W34AZW2LLZGIBD3AVCNFSM6AAAAABI5M2YP6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCMBVGIZDAMJYGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-06-07 19:43 UTC, scianca1 commented
Ahora creo que se actualizo bien

2024-06-08 02:52 UTC, Renzo-Guerra approved these changes

2024-06-09 17:22 UTC, merged