Cicedev 230
ciceunicen/core pull request #88
Opened 2024-06-17 15:02 UTC by Renzo-Guerra

Como personal del CICE quiero recibir una notificación cuando soy cargado como administrador de un proyecto para ponerme en contacto. 
IMPORTANTE: La notificacion no va para los "personal del cice", va para quien sea que haya sido asignado en el proyecto, ya que en el front el form permite seleccionar a los administradores en vez de a gente con rol Personal del CICE, asi que para testearlo asignar en un nuevo proyecto a alguien con rol Admin. 

Que deben revisar de codigo nomas? Los ultimos 3 commits: Ya que los anteriores son de CICEDEV-255 (Recomiendo testear primero CICEDEV-255)
![image](https://github.com/ciceunicen/core/assets/104610425/bd5fa2c2-ac07-4b2e-8190-c038849966d8)

IMPORTANTE PARA MERGEAR: Debido a que necesitaba utilizar el serviceImp de Notificaciones y la entidad Notificaciones, necesitaba unas updates que habia hecho y ya pusheado a CICEDEV-255, pero debido a que todavia no estaban aprobadas, cree la rama CICEDEV-230 a partir de la rama CICEDEV-255 para tener sus actualizaciones y no tener que escribir otra vez el codigo, o tener que esperar hasta que sea aprobada la CICEDEV-255. 

TLDR: mergear primero la CICEDEV-255 y luego la CICEDEV-230.

2024-06-18 14:44 UTC, ciceunicen approved these changes

2024-06-19 16:58 UTC, scianca1 requested changes
no lo pude probar porque, cuando entro con un usuario con rol de admin o superadmin no me aparece la campanita de las notificaciones

2024-06-20 12:14 UTC, Renzo-Guerra commented
Ahi revisé el historial de commits desde develop, para que vean la campana de notificaciones y puedan testear el codigo deben (desde develop) tener el mergeo con la rama CICEDEV-250 (La que permite ver las notificaciones en TODOS los roles), solo deben hacer un git pull desde develop (en WEB) para tener los cambios del front, y ahi si utilizar desde CORE la branch CICEDEV-230

Adjunto el historial de commits y mergeos de develop, a mi me funciona porque ya tenia los ultimos cambios en develop
![image](https://github.com/ciceunicen/core/assets/104610425/d2629020-b3a7-474d-91e6-d52498f6224c)


Testeo que realizé:


El usuario con idUser 2 crea un nuevo proyecto, automaticamente genera 2 notificaciones nuevas en la tabla notificaciones. La que tiene id 52 es la que le va a llegar al administrador, indicandole que se le asignó un nuevo proyecto, y la que tiene id 53 es la que le va a llegar al que creó el proyecto, para indicarle que se creó con exito. NOTA: No recuerdo si lo dije en la ultima daily o en la anteultima, pero la ultima columna de notificacion,  la que se llama "id_administrator" hace referencia de a que id usuario le va a llegar la notificacion.

Adjunto las 2 notificaciones que se generan al crear un proyecto exitosamente
![image](https://github.com/ciceunicen/core/assets/104610425/744943cb-6f41-4033-b925-ea9c74d314c5)

Adjunto como al administrador tambien le llegó la notificacion
![image](https://github.com/ciceunicen/core/assets/104610425/e9be2f34-f194-42e2-b51e-8121f713bd6b)
![image](https://github.com/ciceunicen/core/assets/104610425/649c8d01-2053-449e-9d19-5911a787072f)

2024-06-21 18:09 UTC, scianca1 approved these changes

2024-06-21 18:11 UTC, merged